Repository 11ty/eleventy, pull requests merged in 2022-12, with the labels that each got.

#1537 Make cachePartialFiles and getPartials async
  src/Engines/Custom.js
  src/Engines/Handlebars.js
  src/Engines/JavaScript.js
  src/Engines/Mustache.js
  src/Engines/TemplateEngine.js
Labels: in-progress

#2188 feat: pass file path to custom data parser
  src/TemplateData.js
Labels: needs-changes

#2481 #2386 show custom engine label
  src/TemplateRender.js
Labels: in-progress

#2250 Standardized `this` signature for filters
  src/Engines/Handlebars.js
  src/Engines/JavaScript.js
  src/Engines/Liquid.js
  src/Engines/Nunjucks.js
Labels: feature: 🥸 API consistency
